if vim.g.vscode then
  -- VSCode extension
  local vscode = require("vscode")
  vim.keymap.set({ "n" }, "<space>R", function()
    vscode.action("editor.action.refactor")
  end)
  vim.keymap.set({ "n" }, "<space>r", function()
    vscode.action("editor.action.rename")
  end)
  vim.keymap.set({ "n" }, "gd", function()
    vscode.action("editor.action.goToDeclaration")
  end)
  vim.keymap.set({ "n" }, "gr", function()
    vscode.action("editor.action.goToReferences")
  end)
  vim.keymap.set({ "n" }, "gf", function()
    vscode.action("workbench.action.findInFiles")
  end)
  vim.keymap.set({ "n" }, "<space>e", function()
    vscode.action("revealInExplorer")
  end)
  vim.keymap.set({ "n" }, "gs", function()
    vscode.action("workbench.action.showAllSymbols")
  end)
  vim.keymap.set({ "n" }, "gS", function()
    vscode.action("workbench.action.gotoSymbol")
  end)
  vim.keymap.set({ "n" }, "gi", function()
    vscode.action("editor.action.goToImplementation")
  end)
  vim.keymap.set({ "n" }, "ga", function()
    vscode.action("editor.action.quickFix")
  end)
  vim.keymap.set({ "n" }, "ge", function()
    vscode.action("editor.action.marker.next")
  end)
  vim.keymap.set({ "n" }, "gE", function()
    vscode.action("editor.action.marker.nextInFiles")
  end)
  vim.keymap.set({ "n" }, "g<space>", function()
    vscode.action("closeMarkersNavigation")
  end)
  vim.keymap.set({ "n" }, "<CR>", function()
    vscode.action("workbench.action.files.save")
  end)
  vim.keymap.set({ "n" }, "<space>ft", function()
    vscode.action("terminal.focus")
  end)
else
  -- bootstrap lazy.nvim, LazyVim and your plugins
  require("config.lazy")
end
